# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics (WakaTime)
on:
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED

          # Options
          user: REALalphas
          template: classic
          base: ""
          filename: github-metrics-waka.svg
          base_indepth: yes
          config_octicon: yes
          config_timezone: Europe/Moscow
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: public
          plugin_wakatime_sections: time, projects, languages, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: realalphas
          plugin_wakatime_token: ${{ secrets.WAKATIME_APIKEY }}
